In [ ]:
# list generated from content based
list1 = prediction('A00248626G99Y8GVGKKQ')

In [ ]:
list1

['B01FZ39IVI',
 'B015SXWWRC',
 'B00DAMT23G',
 'B013QNZ1P6',
 'B010JT9UFW',
 'B01ARQ385A',
 'B012Z1F82Q',
 'B00GPSMJIC',
 'B013A4F3Q8',
 'B01G56GOIE']

In [ ]:
df_user_item = pd.read_csv("/content/drive/MyDrive/2nd sem/RS/assignment-3_my/proper/temp_files/data_learning_to_rank.csv")
items = pd.read_pickle("/content/drive/MyDrive/2nd sem/RS/assignment-3_my/proper/temp_files/items_representation.pkl")

In [ ]:
df_user_item

Unnamed: 0         0        1        2    3    4    5         6  \
0                0  0.000000  0.00000  0.36863  0.0  0.0  0.0  0.000000   
1                1  0.000000  0.00000  0.00000  0.0  0.0  0.0  0.000000   
2                2  0.000000  0.00000  0.00000  0.0  0.0  0.0  0.000000   
3                3  0.000000  0.00000  0.00000  0.0  0.0  0.0  0.000000   
4                4  0.000000  0.00000  0.00000  0.0  0.0  0.0  0.000000   
...            ...       ...      ...      ...  ...  ...  ...       ...   
228047      228047  0.000000  0.00000  0.00000  0.0  0.0  0.0  0.000000   
228048      228048  0.000000  0.00000  0.00000  0.0  0.0  0.0  0.718848   
228049      228049  0.000000  0.36921  0.00000  0.0  0.0  0.0  0.000000   
228050      228050  0.212072  0.00000  0.00000  0.0  0.0  0.0  0.421695   
228051      228051  0.000000  1.00000  0.00000  0.0  0.0  0.0  0.000000   

               7         8  ...   43   44   45   46        47        48  \
0       0.000000  0.349135  ...  0.0  0.0  0.0  0.0  0.000000  0.000000   
1       0.000000  0.000000  ...  0.0  0.0  0.0  0.0  0.000000  0.000000   
2       0.380020  0.000000  ...  0.0  0.0  0.0  0.0  0.000000  0.000000   
3       0.000000  0.000000  ...  0.0  0.0  0.0  0.0  0.000000  0.000000   
4       0.262455  0.000000  ...  0.0  0.0  0.0  0.0  0.000000  0.000000   
...          ...       ...  ...  ...  ...  ...  ...       ...       ...   
228047  0.000000  0.000000  ...  0.0  0.0  0.0  0.0  0.000000  0.000000   
228048  0.000000  0.000000  ...  0.0  0.0  0.0  0.0  0.000000  0.000000   
228049  0.239268  0.000000  ...  0.0  0.0  0.0  0.0  0.000000  0.000000   
228050  0.000000  0.000000  ...  0.0  0.0  0.0  0.0  0.158612  0.187795   
228051  0.000000  0.000000  ...  0.0  0.0  0.0  0.0  0.000000  0.000000   

              49        asin      reviewerID  votes  
0       0.368575  7106116521  A3DDWDH9PX2YX2    2.0  
1       0.000000  7106116521  A29HLOUW0NS0EH    5.0  
2       0.000000  B00007GDFV   AHWOW7D1ABO9C    3.0  
3       0.000000  B00007GDFV  A1L5PG0YZ4TNSZ    5.0  
4       0.000000  B00007GDFV   AY49M8RQ2DQEZ    5.0  
...          ...         ...             ...    ...  
228047  0.000000  B01HJEOC9E   AJIM3T62ICOKJ    3.0  
228048  0.000000  B01HJHTH5U   A3L58EEW77KH5    5.0  
228049  0.000000  B01HJHTH5U  A3EH57TD6S6LK4    5.0  
228050  0.184913  B01HJHTH5U   ARI5TGQ03D3NT    4.0  
228051  0.000000  B01HJHTH5U  A3O90PACS7B61K    3.0  

[228052 rows x 54 columns]

In [ ]:
df_temp = df_user_item[df_user_item['asin'].isin(list1)]

In [ ]:
df_temp

Unnamed: 0    0    1    2         3    4    5         6         7  \
127650      127650  0.0  0.0  0.0  0.000000  0.0  0.0  0.703543  0.000000   
133873      133873  0.0  0.0  0.0  0.686914  0.0  0.0  0.000000  0.000000   
177569      177569  0.0  0.0  0.0  0.000000  0.0  0.0  0.703543  0.000000   
181761      181761  0.0  0.0  0.0  0.000000  0.0  0.0  0.424697  0.288975   
182088      182088  0.0  0.0  0.0  0.686914  0.0  0.0  0.000000  0.000000   
183260      183260  0.0  0.0  0.0  0.000000  0.0  0.0  0.703543  0.000000   
189523      189523  0.0  0.0  0.0  0.000000  0.0  0.0  0.703543  0.000000   
204190      204190  0.0  0.0  0.0  0.000000  0.0  0.0  0.703543  0.000000   
222969      222969  0.0  0.0  0.0  0.000000  0.0  0.0  0.703543  0.000000   
223584      223584  0.0  0.0  0.0  0.000000  0.0  0.0  0.502064  0.000000   

          8  ...   43   44   45   46   47   48   49        asin  \
127650  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  B00DAMT23G   
133873  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  B00GPSMJIC   
177569  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  B010JT9UFW   
181761  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  B012Z1F82Q   
182088  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  B013A4F3Q8   
183260  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  B013QNZ1P6   
189523  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  B015SXWWRC   
204190  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  B01ARQ385A   
222969  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  B01FZ39IVI   
223584  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  B01G56GOIE   

                  reviewerID  votes  
127650        A3TWE4VSEGL6BI    5.0  
133873        A3U4MFGKCW1UKP    5.0  
177569        A20CNZ7AM8YNXI    5.0  
181761  A0386579THXZOFNTHNLD    5.0  
182088        A1GBY5L5YQ9OZC    5.0  
183260        A2HVL8JN9MH92X    5.0  
189523        A280KQINTNDKJC    5.0  
204190        A2FYHY2AFDF48W    5.0  
222969         ACEL7N7CGOJB2    4.0  
223584         ABJSY3VF6NBT4    5.0  

[10 rows x 54 columns]

In [ ]:
df_temp = df_temp.drop(['Unnamed: 0'], axis=1)

In [ ]:
import torch
y_train = torch.tensor(df_temp['votes'].values.astype('int64'))
x_train = torch.tensor(df_temp.drop(['asin','reviewerID','votes'], axis = 1).values.astype(np.float32))

In [ ]:
x_train

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7035, 0.0000, 0.0000,
         0.0000, 0.0000, 0.5244, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.4797, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.6869, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.5362, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.4905, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7035, 0.0000, 0.0000,
         

In [ ]:
y_train

tensor([5, 5, 5, 5, 5, 5, 5, 5, 4, 5])

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

class RankNet(nn.Module):
    def __init__(self, num_features):
        super(RankNet, self).__init__()
        self.num_features = num_features
        self.fc1 = nn.Linear(num_features, 32)
        self.fc2 = nn.Linear(32, 16)
        self.fc3 = nn.Linear(16, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.sigmoid(x)
        return x

def pairwise_loss(preds, targets):
    """
    Calculates pairwise loss between predicted and target scores.
    """
    n = len(preds)
    loss = 0.0
    for i in range(n):
        for j in range(i+1, n):
            sij = targets[i] - targets[j]
            pij = preds[i] - preds[j]
            loss += torch.log(1 + torch.exp(-sij * pij))
    return loss

# Initialize model and optimizer
model = RankNet(num_features=50)
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Train the model
num_epochs = 50
for epoch in range(num_epochs):
    # Forward pass
    preds = model(x_train)
    loss = pairwise_loss(preds.squeeze(), y_train.float())

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print progress
    if (epoch+1) % 10 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

Epoch [10/50], Loss: 31.1719
Epoch [20/50], Loss: 31.1434
Epoch [30/50], Loss: 31.1065
Epoch [40/50], Loss: 31.0545
Epoch [50/50], Loss: 30.9804


In [ ]:
print(preds)

tensor([[0.4345],
        [0.5758],
        [0.4345],
        [0.4778],
        [0.5758],
        [0.4345],
        [0.4345],
        [0.4345],
        [0.4345],
        [0.5447]], grad_fn=<SigmoidBackward0>)


In [ ]:
pred = preds.detach().numpy()
pred = pd.DataFrame(pred)
pred['asin'] = list1
suggest = pred.sort_values(by=[0], ascending=False)

In [ ]:
suggest

0        asin
1  0.575830  B015SXWWRC
4  0.575830  B010JT9UFW
9  0.544681  B01G56GOIE
3  0.477754  B013QNZ1P6
0  0.434528  B01FZ39IVI
2  0.434528  B00DAMT23G
5  0.434528  B01ARQ385A
6  0.434528  B012Z1F82Q
7  0.434528  B00GPSMJIC
8  0.434528  B013A4F3Q8